import platform
SYS1 = platform.system()
SYS2 = platform.release()
SYS3 = platform.processor()
SYS4 = platform.node()
SYS5 = platform.python_build()
print("______________")
print("|------------|")
print("|SYSFETCH 0.1|")
print("|------------|")
print(SYS1)
print(SYS2)
print(SYS3)
print(SYS4)
print(SYS5)
print("----------------------------------------")
print("Code Made by 'TheSearcher213' on Github")
print("----------------------------------------")
input("Press Enter to exit.")
