import platform
import time
SYS1 = platform.system()
SYS2 = platform.release()
SYS3 = platform.processor()
SYS4 = platform.node()
SYS5 = platform.python_build()
print("|----------------|")
print(" SYSFETCH MINIMAL")
print("|----------------|")
print("OPERATING SYSTEM: ", SYS1)
print("RELEASE: ", SYS2)
print("PROCESSOR: ", SYS3)
print("DEVICE NAME: ", SYS4)
print("PYTHON INFO: ", SYS5)
print("------------------------------------------")
print("Code by 'TheSearcher213' on Github")
print("Librarys Provided by Python Module Index")
print("------------------------------------------")
time.sleep(5)
