import platform
SYS1 = platform.system()
SYS2 = platform.release()
SYS3 = platform.processor()
SYS4 = platform.node()
SYS5 = platform.python_build()
print("______________")
print("|------------|")
print("|SYSFETCH 0.1|")
print("|------------|")
print("OPERATING SYSTEM: ", SYS1)
print("RELEASE: ", SYS2)
print("PROCESSOR: ", SYS3)
print("DEVICE NAME: ", SYS4)
print("PYTHON INFO: ",  SYS5)
print("----------------------------------------")
print("Code Made by 'TheSearcher213' on Github")
print("----------------------------------------")
input("Press Enter to exit.")
