import platform
import psutil
import time
SYS1 = platform.system()
SYS2 = platform.release()
SYS3 = platform.processor()
SYS4 = platform.node()
SYS5 = platform.python_build()
PT = time.process_time()
PT2 = time.process_time_ns()
TTN = time.thread_time_ns()
CC = psutil.cpu_count()
CCL = psutil.cpu_count(logical=False)
DU = psutil.disk_usage('/')
VM = psutil.virtual_memory()
SM = psutil.swap_memory()
print("______________")
print("|------------|")
print("|SYSFETCH 0.3|")
print("|------------|")
print("OPERATING SYSTEM: ", SYS1)
print("RELEASE: ", SYS2)
print("PROCESSOR: ", SYS3)
print("CPU CORE COUNT: ", CC)
print("CPU LOGICAL CORE COUNT: ", CCL)
print("DEVICE NAME: ", SYS4)
print("PYTHON INFO: ",  SYS5)
print("DISK USAGE (Bytes): ", DU)
print("VIRTUAL MEMORY (Bytes): ", VM)
print("SWAP MEMORY (Bytes): ", SM)
print("PROCESS TIME: ", PT)
print("PROCESS TIME IN NS: ", PT2)
print("THREAD TIME IN NS: ", TTN)
print("----------------------------------------")
print("Code Made by 'TheSearcher213' on Github")
print("Librarys Provided by Python Module Index")
print("----------------------------------------")
time.sleep(10)
